# Generated by Django 6.0.4 on 2026-05-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20260402_1242'),
        ('blog', '0002_auto_20260501_1132'),
    ]

    operations = [
    ]
